### ISSUE TITLE
The reference of node name

### ISSUE THREAD

**Issue by YuChaode** [lllyfeng/incident-management#1]
The reference of node name should take some more considerations.
Currently, the reference of node is pointing to the node name defined in enterprise network inventory draft. 
  typedef node-ref {
    type leafref {
      path "/nw:networks/nw:network/nw:node/nw-inv:name";
    }
    description "reference a network node.";
  }

It is a little bit strange while adopting this model in operators' network. And there are still some arguments of the modeling of network inventory. We'd better wait for the conclusion of NIMBY. And then choose the fundamental model to reference.
Or we can reference the node-id defined in network model.

**Comment by lllyfeng** [comment]
ok. I have changed to node-id
